[package]
name = "hello-rust"
version = "0.1.0"
authors = ["theneoterik <shihaanws@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
walkdir = "2.3.1"
